```{r}
library(reshape2)
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
library(reshape2)

## List files in directory for read in
f <- list.files("../bcd_2019_10_01/bcd/")
length(f)

```

```{r}
for (file in file_list){
       
  # if the merged dataset doesn't exist, create it
  if (!exists("dataset")){
    dataset <- read.csv(paste0("../bcd_2019_10_01/bcd/", file), header=TRUE)
    print("Does not exist")
  }
   
  # if the merged dataset does exist, append to it
  if (exists("dataset")){
    temp_dataset <-read.csv(paste0("../bcd_2019_10_01/bcd/", file), header=TRUE)
    dataset<-rbind(dataset, temp_dataset)
    rm(temp_dataset)
  }
 
}
dim(dataset)  
head(dataset)
```

```{r}
## Just so you can play with data inputed files without reading them in again
dataset1 <- dataset

## Ways to view and understand dataset
head(dataset1)
dim(dataset1)
str(dataset1)
colnames(dataset1)

head(dataset)
dataset1 %>% 
  separate(species_y, c("region", "enhancer_func", "species")) %>%
  select(-c("X")) 

dataset1 <- dataset1 %>% 
  separate(species_y, c("region", "enhancer_func", "species")) %>% 
 
  select(-c("X")) ##gets rid of column X

head(dataset1)
```

```{r}
rawseq <- dataset1 %>%
  group_by(raw_seq)
rawseq

#convert all factors to lowercase
rawseq$seq_lower = tolower(rawseq$raw_seq)
rawseq

#group by lowercase factors and sum over n
grouped_seq <- rawseq %>%
  group_by(seq_lower) %>% 
  mutate(n= n()) %>% 
     distinct(seq_lower, .keep_all=TRUE)
grouped_seq

#order by decreasing n
ordered_seq <- grouped_seq[with(grouped_seq, order(-n)), ]
ordered_seq

#create a column containing lists of bases
ordered_seq$split_seq = strsplit(ordered_seq$seq_lower, "")
ordered_seq

#assign a column to each base based on position
pos_seq <- ordered_seq %>% 
  separate(split_seq, c("pos0", "pos1", "pos2", "pos3", "pos4", "pos5", "pos6")) %>%
  select(-c("pos0"))
pos_seq

pos_seq_reshaped <- melt(pos_seq, measure.vars = c("pos1", "pos2", "pos3", "pos4", "pos5", "pos6"))

pos_seq_groups <- pos_seq_reshaped %>% group_by(enhancer_func, variable) %>%
             mutate(group_size = n()) %>%
             group_by(variable, value, enhancer_func) %>%
             summarise(perc = n()/max(group_size))

colnames(pos_seq_groups)[colnames(pos_seq_groups)=="variable"] <- "positions"
colnames(pos_seq_groups)[colnames(pos_seq_groups)=="value"] <- "nucleotides"
colnames(pos_seq_groups)[colnames(pos_seq_groups)=="perc"] <- "percentage"

pos_seq_groups

ggplot(data=pos_seq_groups, aes(fill=enhancer_func, y=percentage, x=nucleotides)) + 
  geom_bar(stat="identity", position="dodge") + 
  scale_y_continuous(labels = scales::percent) + 
  facet_grid(~positions)
```